/*
 * Automatically generated by 'ng g ng-alain:plugin icon'
 */

import {
  AlipayCircleOutline,
  AppstoreOutline,
  CopyrightOutline,
  DeleteFill,
  DownloadOutline,
  EditFill,
  FileAddFill,
  FileExcelOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MessageOutline,
  ReloadOutline,
  RollbackOutline,
  SaveFill,
  SettingOutline,
  TaobaoCircleOutline,
  UserOutline,
  WeiboCircleOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  AlipayCircleOutline,
  AppstoreOutline,
  CopyrightOutline,
  DeleteFill,
  DownloadOutline,
  EditFill,
  FileAddFill,
  FileExcelOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MessageOutline,
  ReloadOutline,
  RollbackOutline,
  SaveFill,
  SettingOutline,
  TaobaoCircleOutline,
  UserOutline,
  WeiboCircleOutline
];
